### ISSUE TITLE
Step parameter converted to number datatype in case the parameter string is all numbers.

### ISSUE THREAD

**Issue by kiranpatil-ic** [getgauge/gauge-ts#189]
**Describe the bug**
E.g `* Set filter to "4578"`

We use the parameter in such a way that you can specify comma separated values & we split them in the step definition. But since updating to the latest gauge/ts, steps where the string parameter is all numeric have started failing.

```
    @Step("Set filter to <commaSeparatedSites>")
    async setFilter(commaSeparatedSites: string) {
        const sitesArray = commaSeparatedSites.split(','); //FAILURE POINT
        //Loop through array & set filter to the specified values
    }
```

**Expected behavior**
The parameter should be parsed as string even though the string is all numeric.

```
Gauge version: 1.6.7
Plugins
-------
html-report (4.3.1)
screenshot (0.3.0)
ts (0.3.4)
xml-report (0.5.1)
```

```
 - Windows 11
 - VSCode Codelens
 - VSCode

**Comment by BugDiver** [comment]
For me, this seems like an expected behaviour and that's how it works in other gauge plugins (java, c# etc).
If there is requirement that Number strings should be parsed as string only, I think the user cat create a custom parameter parser, and return the string as it is. The CustomParameterParser get precedence over native or other internal parsers.
